### ISSUE TITLE
Observable Plot

### ISSUE THREAD

**Issue by ttodosi** [tmcw/obsidian-iframe-plugin#10]
Hey any chance you can share how to get this example going in freeform? or something similar? giving me and the ai bots grief. looking to use it for maps and stuff
https://observablehq.com/@observablehq/plot-floor-plan

> Importing a module from esm.sh
> Most npm modules that are compatible with browsers are available from
> https://esm.sh/, jsdelivr, unpkg, or skypack. **Observable Plot** is an especially
> tricky one, but most "just work."

**Comment by tmcw** [comment]
Sure, this example works basically verbatim:

```js
import * as Plot from "https://cdn.jsdelivr.net/npm/@observablehq/plot@0.6/+esm";

const westport = await fetch('https://tmcw-drop.s3-us-west-1.amazonaws.com/westport.json').then(r => r.json());

display(Plot.geo(westport).plot({projection: {type: "identity", domain: westport}}))
```

**Comment by ttodosi** [comment]
you rock!
![image](https://github.com/tmcw/obsidian-freeform/assets/118843813/c12bd827-982a-4d07-86aa-b9c0891f8c61)
